# Generated by Django 5.0.6 on 2024-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=0, upload_to='uploadimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
