# Generated by Django 5.0.6 on 2024-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_alter_project_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.CharField(choices=[('Not started', 'Not Started'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Not Started', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=0, upload_to='uploadimages/projects/'),
        ),
    ]
