# Generated by Django 5.0.6 on 2024-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_type_project_category_project_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Team', 'Team')], default='Private', max_length=100),
        ),
    ]
