# Generated by Django 5.0.6 on 2024-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(choices=[('Not started', 'Not Started'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered')], default='Not Started', max_length=100),
        ),
    ]
