# Generated by Django 5.0.6 on 2024-09-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_users_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team_members',
            new_name='team_member',
        ),
    ]
