# Generated by Django 5.0.6 on 2024-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_employee_image_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expertise',
            field=models.CharField(default='', max_length=100),
        ),
    ]
