# Generated by Django 5.0.6 on 2024-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_employee_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
