# Generated by Django 5.0.6 on 2024-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(default='', max_length=100),
        ),
    ]
