# Generated by Django 5.0.6 on 2024-06-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saraj', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
