# Generated by Django 5.0.6 on 2024-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_rename_issue_description_issue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attachment',
            field=models.FileField(default=0, upload_to='uploadimages/projects/'),
        ),
    ]
