# Generated by Django 5.0.6 on 2024-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_issue_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attachment',
            field=models.FileField(default=0, upload_to='uploadimages/kanban_issue/'),
        ),
    ]
