# Generated by Django 5.0.6 on 2024-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_issue_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='attachment',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
