# Generated by Django 5.0.6 on 2024-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_remove_issue_attachment_issue_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
