# Generated by Django 5.0.6 on 2024-09-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check2',
        ),
        migrations.AddField(
            model_name='room',
            name='user1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='user2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
