# Generated by Django 5.0.6 on 2024-09-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_room_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='team_members',
            new_name='friends',
        ),
    ]
