# Generated by Django 5.0.6 on 2024-09-13 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_for',
            field=models.ManyToManyField(default='all', related_name='event_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
